# syntax = docker/dockerfile:1.3
FROM node:12-alpine AS deps
WORKDIR /var/www
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm install


FROM node:12-alpine AS builder
WORKDIR /var/www
COPY --from=deps /var/www .
COPY . .
ENV NODE_ENV=production
# RUN --mount=type=cache,target=./node_modules/.cache npm run build
RUN npm run build
#COPY --chown=101  /var/www/dist /vagrant/tmp/www/
#RUN npm run serve
#EXPOSE 8080

FROM ghcr.io/rabotaru/dochub/nginx:v0.0.3 as nginx
COPY --chown=101 --from=builder /var/www/dist /usr/share/nginx/html
EXPOSE 8079