# syntax = docker/dockerfile:1.3
ARG NODE_VERSION=13

FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /var/www
COPY package*.json ./
RUN npm install
COPY ./ .
ENV NODE_ENV=production
#RUN npm install core-js@3.23.5
RUN npm run build
#CMD ["npm", "run", "serve"]
#CMD ["sh"]
#EXPOSE 8080


FROM ghcr.io/rabotaru/dochub/nginx:v0.0.3 as nginx
#COPY  /vagrant/pics /usr/share/nginx/html/pics
#COPY --chown=101 --from=builder /vagrant/pics /usr/share/nginx/html/pics
COPY --chown=101 --from=builder /var/www/dist /usr/share/nginx/html
#COPY dist_tmp /usr/share/nginx/html
COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY ssl /etc/nginx/ssl
EXPOSE 8079